"""Build signals out of sine waves and look at their frequency content.

YOU BUILD THIS. It is Lab 1.

Every function below raises until you implement it, so `pytest` runs and shows
you exactly which of the seven checks in tests/test_spectrum.py still fail.
That failing list is your specification — the app is finished when it is empty.

Do not edit this file by hand at the start. Ask your agent, following
labs/PROMPTS.md, and read what it writes.
"""

TODO = "You build this in Lab 1. See labs/LAB1.md and tests/test_spectrum.py."


def make_signal(components, fs, duration):
    """Add sine waves together.

    components is a list of (frequency in hertz, amplitude) pairs.
    fs is the sampling rate in samples per second.
    Should return the time values and the signal values.
    """
    raise NotImplementedError(TODO)


def spectrum(signal, fs):
    """Return the frequencies present in the signal, and how strong each is.

    Should return (freqs, magnitudes).
    """
    raise NotImplementedError(TODO)


def peak_frequency(freqs, magnitudes):
    """The frequency with the most energy in it."""
    raise NotImplementedError(TODO)
